jobs:
- job: Build
  pool:
    vmImage: 'VS2017-Win2016'
  
  steps:
  - task: BatchScript@1
    displayName: 'VCPKG CLONE'
  - script: git clone https://github.com/Microsoft/vcpkg.git && cd vcpkg

  - task: BatchScript@1
    displayName: 'VCPKG Bootstrap'
    inputs:
        filename: 'bootstrap-vcpkg.bat'

  - script: vcpkg.exe install --triplet $(arch)-windows-static $(deps)
    displayName: 'Build Dependencies'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: 'installed'
      includeRootFolder: false
      replaceExistingArchive: true
      archiveType: '7z'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(deps)-$(arch).7z'

  - task: PublishBuildArtifacts@1
    inputs:
        artifactName: '$(deps)-$(arch)'

- job: Publish
  pool:
    vmImage: 'VS2017-Win2016'
    
  dependsOn: Build
  steps:
    - task: BatchScript@1
      displayName: 'Publish to GitHub'
    - script: echo wat
