jobs:
- job: Build
  pool:
    vmImage: 'VS2017-Win2016'
  
  timeoutInMinutes: 180

  strategy:
    matrix:
      Qt5 x64:
        arch: x64
        deps: qt5-base qscintilla
      EGM deps x64:
        arch: x64
        deps: pugixml rapidjson yaml-cpp protobuf grpc
      EMAKE deps x64: 
        arch: x64
        deps: boost
      Qt5 x86:
        arch: x86
        deps: qt5-base qscintilla
      EGM deps x86:
        arch: x86
        deps: pugixml rapidjson yaml-cpp protobuf grpc
      EMAKE deps x86: 
        arch: x86
        deps: boost
  
  steps:
  - script: git.exe clone https://github.com/Microsoft/vcpkg.git && cd vcpkg
    displayName: 'VCPKG Clone'

  - task: BatchScript@1
    displayName: 'VCPKG Bootstrap'
    inputs:
        filename: 'vcpkg\bootstrap-vcpkg.bat'

  - script: |
      :repeat 
      vcpkg\vcpkg.exe install --triplet $(arch)-windows-static $(deps) || goto :repeat
    displayName: 'Build Dependencies'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: 'C:\vcpkg\installed'
      includeRootFolder: false
      replaceExistingArchive: true
      archiveType: '7z'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(deps)-$(arch).7z'

  - task: PublishBuildArtifacts@1
    inputs:
        artifactName: '$(deps)-$(arch)'

- job: Publish
  pool:
    vmImage: 'VS2017-Win2016'
    
  dependsOn: Build
  steps:
    - task: BatchScript@1
      displayName: 'Publish to GitHub'
    - script: echo wat
