jobs:
- job: Build
  pool:
    vmImage: 'VS2017-Win2016'
  
  timeoutInMinutes: 180

  strategy:
    matrix:
      EGM deps x64:
        arch: x64
        deps: pugixml rapidjson
      EMAKE deps x64: 
        arch: x64
        deps:  yaml-cpp
      EGM deps x86:
        arch: x86
        deps: pugixml rapidjson
      EMAKE deps x86: 
        arch: x86
        deps: yaml-cpp
  
  steps:
  - script: git.exe clone https://github.com/Microsoft/vcpkg.git && cd vcpkg
    displayName: 'VCPKG Clone'

  - task: BatchScript@1
    displayName: 'VCPKG Bootstrap'
    inputs:
        filename: 'vcpkg\bootstrap-vcpkg.bat'

  - script: |
      :repeat 
      vcpkg\vcpkg.exe install --triplet $(arch)-windows-static $(deps) || goto :repeat
    displayName: 'Build Dependencies'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: 'C:\vcpkg\installed'
      includeRootFolder: false
      replaceExistingArchive: true
      archiveType: '7z'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(deps)-$(arch).7z'

  - task: PublishBuildArtifacts@1
    inputs:
        artifactName: '$(deps)-$(arch)'

- job: Publish
  pool:
    vmImage: 'VS2017-Win2016'
    
  dependsOn: Build
  steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      artifactName: |
        'yaml-cpp-x64'
        'pugixml rapidjson-x64'
        'yaml-cpp-x86'
        'pugixml rapidjson-x86'
    
  - script: |
      7z x *.zip -aoa
      mkdir -p x64/installed/
      cd x64/installed
      7z x ../*x64/*.7z -aoa
    
      cd ../../
    
      mkdir -p x86/installed/
      cd x86/installed
      7z x ../*x86/*.7z -aoa
    
      cd ../../
    
      7z a rgmdeps-x64.7z x64/installed/
      7z a rgmdeps-x64.7z x86/installed/
    displayName: 'Repackage Dependencies'
  
  - task: GithubRelease@0 
    displayName: 'Create GitHub Release'
    inputs:
      githubConnection: rgm-deps
      repositoryName: enigma-dev/RadialGM-deps
      tagSource: manual
      tag: $(Build.BuildNumber)      
      assets: |
          rgmdeps-x64.7z
          rgmdeps-x86.7z