jobs:
- job: Build
  pool:
    vmImage: 'ubuntu-16.04'
  
  timeoutInMinutes: 180
  
  steps:
  - script: git clone https://github.com/Microsoft/vcpkg.git
    displayName: 'VCPKG Clone'
  
  - task: GithubRelease@0 
    displayName: 'Create GitHub Release'
    inputs:
      githubConnection: rgmdeps
      repositoryName: enigma-dev/RadialGM-deps
      tagSource: manual
      tag: $(Build.BuildNumber)      
      assets: 'vcpkg\bootstrap-vcpkg.bat'
